// assets/mock + assets/onboarding/battery.json -> data/mock.js (生成は一方向。
// 正は本体 repo の assets 側で、ここを手編集しない — .claude/rules/mock-data.md)
//
//   node lib-design/handoff/AppFlow/tools/build-data.mjs
//
// 本体 repo に入れ子で clone された lib-design/ から実行する前提 (../../../../assets)。

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const appRoot = resolve(here, '../../../..');
const out = resolve(here, '../data/mock.js');

const read = (p) => JSON.parse(readFileSync(resolve(appRoot, p), 'utf8'));

const partners = read('assets/mock/partner/partners.json');
const timelines = read('assets/mock/timeline/timelines.json');
const reports = read('assets/mock/match/reports.json');
const today = read('assets/mock/theme/today.json');
const schedule = read('assets/mock/theme/schedule.json');
const profile = read('assets/mock/profile/myProfile.json');
const persona = read('assets/mock/persona/card.json');
const battery = read('assets/onboarding/battery.json');

// 重み (types / natures / weakness / visual) は UI に出ないので落とす。
// 落とさないと 44KB の判定テーブルまで design 側に流れ込む
const questions = battery.questions.map((q) => ({
  id: q.id,
  text: q.text,
  input: q.input ?? 'single',
  domain: q.domain ?? null,
  key: q.key ?? '',
  core: q.core ?? false,
  highlight: q.highlight ?? false,
  allowFree: q.allowFree ?? true,
  maxPick: q.maxPick ?? 3,
  options: (q.options ?? []).map((o) => ({ label: o.label, value: o.value ?? '' })),
}));

const data = {
  partners,
  timelines,
  matchReports: reports.reports,
  todayTheme: today,
  themeSchedule: schedule,
  myProfile: profile,
  persona,
  battery: {
    highlightSub: battery.highlightSub,
    closing: battery.closing,
    questions,
  },
};

const banner = `// GENERATED by tools/build-data.mjs — DO NOT EDIT.
// Source of truth: the_last_three/assets/mock/** + assets/onboarding/battery.json
// 再生成: node lib-design/handoff/AppFlow/tools/build-data.mjs
`;

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, `${banner}window.LT3_MOCK = ${JSON.stringify(data, null, 2)};\n`, 'utf8');

const kb = (readFileSync(out).length / 1024).toFixed(1);
console.log(`wrote data/mock.js (${kb} KB) — ${questions.length} questions, ${partners.length} partners`);
